### ISSUE TITLE
Project and Coding profile images are not working.

### ISSUE THREAD

**Issue by HarshUmpoxy** [HarshUmpoxy/Portfolio#1]
Inside the My projects section, I have made a projectData object containing images path of all projects. This object is looped through and images are extracted but it is unable to load. Same is the case with coding profile images of different platforms.

**This is the object**

`const projectData = [
    {
      id: 1,
      title: "SocialEcho",
      image: "../../assets/SocialEcho.jpg",
      ...
`

**Here goes the looping**
`{projectData.map((eachObj) => {
          return (
            <div className="innerContainer" key={eachObj.id}>
              <div className="project-image alignCenter">
                <img src={eachObj.image} alt={eachObj.title} width={350} />
              </div>`

Can anyone point out the correction here.

**Comment by cangdt-agg** [comment]
Can you deliver it to me?

**Comment by cangdt-agg** [comment]
I finished it

![image](https://github.com/HarshUmpoxy/Portfolio/assets/151502470/8defc847-6d92-4884-8db5-03a86b5769c5)
